Korean slide update
hashicorp/field-workshops-vault pull request #65
Opened 2021-09-29 14:49 UTC by Great-Stone

Added link providing guidance added to the original
Fixed incorrect typography in some documents

2021-09-29 14:49 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/field-workshops-vault?pullRequest=65)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/field-workshops-vault?pullRequest=65)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Administrator** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/field-workshops-vault?pullRequest=65).</sub>

2021-09-29 15:25 UTC, rberlind requested changes
@Great-Stone : You seems to be keeping a permanent korean branch.  But by making changes in it, you lost changes I had made to the korean slides in the main branch.  Could you delete your korean branch, create a new one from the main branch, and then make your changes again?

2021-09-30 01:15 UTC, Great-Stone commented
I will fixed from main branch.

2021-09-30 01:15 UTC, closed without merging

2021-09-30 13:35 UTC, rberlind commented
Thanks
Roger

On Wed, Sep 29, 2021 at 9:15 PM Gyuseok Lee ***@***.***>
wrote:

> I will fixed from main branch.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/field-workshops-vault/pull/65#issuecomment-930665284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUF35A7CGD7HS332E2YQCDUEO22FANCNFSM5FACOA6Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>